### ISSUE TITLE
Execution crashes (unsupported operand type(s) for +: 'NoneType' and 'unicode')

### ISSUE THREAD

**Issue by kaiserleo** [ksindi/flask-sqlacodegen#16]
The same database can be processed by sqlacodegen
Let me know if I can provide more details about the issue (without sharing data).

```
Traceback (most recent call last):
  File "/home/leonardo/code/url-controller/venv/bin/flask-sqlacodegen", line 11, in <module>
    sys.exit(main())
  File "/home/leonardo/code/url-controller/venv/lib/python2.7/site-packages/sqlacodegen/main.py", line 59, in main
    args.flask, ignore_cols, args.noclasses)
  File "/home/leonardo/code/url-controller/venv/lib/python2.7/site-packages/sqlacodegen/codegen.py", line 606, in __init__
    model = ModelClass(table, links[table.name], inflect_engine, not nojoined)
  File "/home/leonardo/code/url-controller/venv/lib/python2.7/site-packages/sqlacodegen/codegen.py", line 335, in __init__
    relationship_ = ManyToManyRelationship(self.name, target_cls, association_table, inflect_engine)
  File "/home/leonardo/code/url-controller/venv/lib/python2.7/site-packages/sqlacodegen/codegen.py", line 501, in __init__
    self.kwargs['secondary'] = repr(assocation_table.schema + '.' + assocation_table.name)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'unicode'
```

**Comment by ksindi** [comment]
Hi @kaiserleo unfortunately I can't reproduce your error. Were you able to resolve it?

**Comment by autoferrit** [comment]
I got this error when someone decided to have a primary key defined on a field, as well as an additional index on the same field. removing the index fixed the issue
