### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by devyash** [ksindi/flask-sqlacodegen#18]
I am trying to generate a flask-sqlalchemy for an existing mysql db.
I used the following command
```flask-sqlacodegen --outfile rcdb.py mysql://username:password@hostname/tablename```

The project uses python 3.4. Any clues?

```Traceback (most recent call last):
  File "/var/www/devaccess/py_api/ds/venv/bin/flask-sqlacodegen", line 11, in <module>
    sys.exit(main())
  File "/var/www/devaccess/py_api/ds/venv/lib/python3.4/site-packages/sqlacodegen/main.py", line 59, in main

Traceback (most recent call last):
  File "/var/www/devaccess/py_api/ds/venv/bin/flask-sqlacodegen", line 11, in <module>
    sys.exit(main())
  File "/var/www/devaccess/py_api/ds/venv/lib/python3.4/site-packages/sqlacodegen/main.py", line 59, in main
    args.flask, ignore_cols, args.noclasses)
  File "/var/www/devaccess/py_api/ds/venv/lib/python3.4/site-packages/sqlacodegen/codegen.py", line 606, in __init__
    model = ModelClass(table, links[table.name], inflect_engine, not nojoined)
  File "/var/www/devaccess/py_api/ds/venv/lib/python3.4/site-packages/sqlacodegen/codegen.py", line 335, in __init__
    relationship_ = ManyToManyRelationship(self.name, target_cls, association_table, inflect_engine)
  File "/var/www/devaccess/py_api/ds/venv/lib/python3.4/site-packages/sqlacodegen/codegen.py", line 501, in __init__
    self.kwargs['secondary'] = repr(assocation_table.schema + '.' + assocation_table.name)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by ksindi** [comment]
Take a look at the response in #16 to see if that solves the problem.

**Comment by devyash** [comment]
Hi ksindi,
Thank you for your reply. I saw the issue #16 . I cannot modify the DB. Sqlacodegen worked fine, but flasksqlacode shows the above error.

**Comment by pwall27** [comment]
Take a look how did I fix it at: https://github.com/pwall27/flask-sqlacodegen

**Comment by ksindi** [comment]
thanks @pwall27 will review tonight

**Comment by devyash** [comment]
Hi Pwall27. Thank you for your reply. Modifying the DB is not possible as I don't have a write access on the DB.(Because of sensitive data issue).
Is there any other solutions? I am able to generate using sqlacodegen (without flask extension).

**Comment by devyash** [comment]
@ksindi @pwall27 Thank you.
