### ISSUE TITLE
Error generating model for mssql+pymssql database on which sqlacodegen worked

### ISSUE THREAD

**Issue by pekof** [ksindi/flask-sqlacodegen#29]
Generating model using flask-sqlacodegen==1.1.6.1 failed, but with  I successfully generated model with 
sqlacodegen-1.1.6

Same error with and without --flask option

btw
sqlalchemy==1.1.13
 
```
Traceback (most recent call last):
  File "c:\users\frane\appdata\local\continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\frane\appdata\local\continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\frane\AppData\Local\Continuum\Anaconda3\Scripts\flask-sqlacodegen.exe\__main__.py", line 9, in <module>
  File "c:\users\frane\appdata\local\continuum\anaconda3\lib\site-packages\sqlacodegen\main.py", line 59, in main
    args.flask, ignore_cols, args.noclasses)
  File "c:\users\frane\appdata\local\continuum\anaconda3\lib\site-packages\sqlacodegen\codegen.py", line 606, in __init__
    model = ModelClass(table, links[table.name], inflect_engine, not nojoined)
  File "c:\users\frane\appdata\local\continuum\anaconda3\lib\site-packages\sqlacodegen\codegen.py", line 335, in __init__
    relationship_ = ManyToManyRelationship(self.name, target_cls, association_table, inflect_engine)
  File "c:\users\frane\appdata\local\continuum\anaconda3\lib\site-packages\sqlacodegen\codegen.py", line 501, in __init__
    self.kwargs['secondary'] = repr(assocation_table.schema + '.' + assocation_table.name)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by ksindi** [comment]
@pekof Thanks for letting me know. Take a look at the response in #16 to see if that solves the problem.

**Comment by ksindi** [comment]
@pekof I think the fix would be:
```
self.kwargs['secondary'] = repr(prefix + assocation_table.name) if assocation_table.name is not None else repr(assocation_table.name)
```
Can you see if that works?

**Comment by pekof** [comment]
@ksindi I tried that and got `NameError: name 'prefix' is not defined`
Then I replaced line with
`self.kwargs['secondary'] = repr(assocation_table.schema + assocation_table.name) if assocation_table.schema is not None else repr(assocation_table.name)`
and now it generated model.
Thank you for idea

**Comment by pekof** [comment]
Generated model had some issues but it was solvable by replacing `db.UNIQUEIDENTIFIER`  with `UNIQUEIDENTIFIER` and  `db.BIT` with `BIT` in generated code

**Comment by ksindi** [comment]
Great. Thanks for letting me know. Hope to push out a fix this week.
