### ISSUE TITLE
I'm getting this error (KeyError: 0), any clue?

### ISSUE THREAD

**Issue by oblitum** [ksindi/flask-sqlacodegen#8]
Python 2:
```
sqlacodegen --flask mysql://root:123456@localhost/sample                                                                                     master
Traceback (most recent call last):
  File "/home/francisco/.pyenv/versions/sqlacodegen/bin/sqlacodegen", line 9, in <module>
    load_entry_point('sqlacodegen==1.1.5rc2', 'console_scripts', 'sqlacodegen')()
  File "/home/francisco/.pyenv/versions/sqlacodegen/lib/python2.7/site-packages/sqlacodegen/main.py", line 57, in main
    args.flask, fkcols)
  File "/home/francisco/.pyenv/versions/sqlacodegen/lib/python2.7/site-packages/sqlacodegen/codegen.py", line 597, in __init__
    model = ModelClass(table, links[table.name], inflect_engine, not nojoined)
  File "/home/francisco/.pyenv/versions/sqlacodegen/lib/python2.7/site-packages/sqlacodegen/codegen.py", line 319, in __init__
    relationship_ = ManyToOneRelationship(self.name, target_cls, constraint, inflect_engine)
  File "/home/francisco/.pyenv/versions/sqlacodegen/lib/python2.7/site-packages/sqlacodegen/codegen.py", line 455, in __init__
    colname = constraint.columns[0]
  File "/home/francisco/.pyenv/versions/sqlacodegen/lib/python2.7/site-packages/sqlalchemy/util/_collections.py", line 193, in __getitem__
    return self._data[key]
KeyError: 0
```
Python 3:
```
sqlacodegen --flask mysql://root:123456@localhost/sample 
Traceback (most recent call last):
  File "/home/francisco/.pyenv/versions/flask/bin/sqlacodegen", line 9, in <module>
    load_entry_point('sqlacodegen==1.1.5rc2', 'console_scripts', 'sqlacodegen')()
  File "/home/francisco/.pyenv/versions/flask/lib/python3.4/site-packages/sqlacodegen/main.py", line 57, in main
    args.flask, fkcols)
  File "/home/francisco/.pyenv/versions/flask/lib/python3.4/site-packages/sqlacodegen/codegen.py", line 597, in __init__
    model = ModelClass(table, links[table.name], inflect_engine, not nojoined)
  File "/home/francisco/.pyenv/versions/flask/lib/python3.4/site-packages/sqlacodegen/codegen.py", line 319, in __init__
    relationship_ = ManyToOneRelationship(self.name, target_cls, constraint, inflect_engine)
  File "/home/francisco/.pyenv/versions/flask/lib/python3.4/site-packages/sqlacodegen/codegen.py", line 455, in __init__
    colname = constraint.columns[0]
  File "/home/francisco/.pyenv/versions/flask/lib/python3.4/site-packages/sqlalchemy/util/_collections.py", line 193, in __getitem__
    return self._data[key]
KeyError: 0
```

**Comment by Janzert** [comment]
Given this was the top google result when searching for my own similiar traceback here's what I've found after some digging. The problem seems to result from sqlalchemy changing the type of `constraint.columns` from a simple list to a `ColumnCollection` in version 1.0[1]. If all you need is the column name the change to make is simply replacing `constraint.columns` with `constraint.column_keys`.

[1] http://docs.sqlalchemy.org/en/rel_1_0/changelog/migration_10.html?highlight=columncollection#foreignkeyconstraint-columns-is-now-a-columncollection

**Comment by ksindi** [comment]
Thanks @Janzert. I'm going to mark this as closed.

**Comment by ablekh** [comment]
Hello, @Janzert and @ksindi. I experienced the same error as the OP. I followed @Janzert's recommendation above and replaced all instances of `constraint.columns` with `constraint.column_keys` in `codegen.py` (there seem to be no other files affected). Then I tried to reinstall the package via `python setup.py install`. However, the change results in `KeyError = 0` error going away, but another error appearing, as follows:

```
Traceback (most recent call last):
  File "/usr/local/bin/sqlacodegen", line 9, in <module>
    load_entry_point('sqlacodegen==1.1.5.pre2', 'console_scripts', 'sqlacodegen')()
  File "/usr/local/lib/python2.7/dist-packages/sqlacodegen-1.1.5.pre2-py2.7.egg/sqlacodegen/main.py", line 57, in main
    args.flask, fkcols)
  File "/usr/local/lib/python2.7/dist-packages/sqlacodegen-1.1.5.pre2-py2.7.egg/sqlacodegen/codegen.py", line 597, in __init__
    model = ModelClass(table, links[table.name], inflect_engine, not nojoined)
  File "/usr/local/lib/python2.7/dist-packages/sqlacodegen-1.1.5.pre2-py2.7.egg/sqlacodegen/codegen.py", line 313, in __init__
    for constraint in sorted(table.constraints, key=_get_constraint_sort_key):
  File "/usr/local/lib/python2.7/dist-packages/sqlacodegen-1.1.5.pre2-py2.7.egg/sqlacodegen/codegen.py", line 74, in _get_constraint_sort_key
    return constraint.__class__.__name__[0] + repr(constraint.column_keys)
AttributeError: 'PrimaryKeyConstraint' object has no attribute 'column_keys'
```

Am I missing something? I would appreciate any help in fixing this issue.

**Comment by ksindi** [comment]
@ablekh Just merged @con-av PR which might fix the issue.

**Comment by ablekh** [comment]
@ksindi Thank you. How to correctly apply your recent merge: just reinstall the software (`git pull origin master`, followed by `python setup.py install`)? If so, do I still need to rename `constraint.columns` into `constraint.column_keys`?

**Comment by ksindi** [comment]
@ablekh correct that should work. Check that it's version 1.1.6 in `__init__.py`. I don't think you need to rename but I'm not entirely sure re the issue you're facing.

**Comment by ablekh** [comment]
@ksindi Just tested. I stashed my prior changes (var renaming), updated my local repository, rebuilt and reinstalled the software. Happy to report that it works fine without the prior changes (so I'll just discard them). I was able to successfully auto-generate models - thank you for all your work and help! Now I just hope that the generated models will work well with other modules in my Flask-AppBuilder (FAB) application, but that's another story... (BTW, do you have any experience with FAB, by any chance?)

**Comment by ksindi** [comment]
@ablekh glad to hear it works! Big thanks to @con-av for the PR. Unfortunately I don't think much about FAB.
